import type { Metadata } from "next";
import { Inter } from 'next/font/google'
import "./globals.css";
import Providers from "./providers";
import Footer from "../components/layouts/footer/Footer";
import HeaderWrapper from "../components/layouts/header/HeaderWrapper";
import SupportChatbot from "../components/SupportChatbot"; // 👈 AGREGA ESTA LÍNEA

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
      <html lang="es" className="light" style={{ colorScheme: "light" }}>
      <body className={inter.className}>
        <Providers>
          <HeaderWrapper />
          <main>{children}</main>
          <Footer />
          <SupportChatbot /> 
        </Providers>
      </body>
    </html>
  );
}