import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import Footer from "../components/layouts/footer/Footer";
import HeaderWrapper from "../components/layouts/header/HeaderWrapper"; // 👈 usamos el wrapper

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <body className={inter.className}>
        <Providers>
          <HeaderWrapper /> {/* 👈 ahora el header se oculta solo en ciertas rutas */}
          <main>{children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
